
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 11 21:16:19 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 19;
  public static final int PLUSPLUS = 30;
  public static final int CONST = 47;
  public static final int CASE = 27;
  public static final int LPAREN = 7;
  public static final int SEMI = 5;
  public static final int CONTINUE = 28;
  public static final int MINUS = 33;
  public static final int RPAREN = 8;
  public static final int GRE = 41;
  public static final int FULL = 6;
  public static final int AND = 49;
  public static final int RBOX = 11;
  public static final int OR = 48;
  public static final int LO = 42;
  public static final int COMMA = 9;
  public static final int CLASS = 45;
  public static final int DIV = 35;
  public static final int PLUS = 32;
  public static final int IF = 21;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 31;
  public static final int RETURN = 14;
  public static final int EQUAL = 15;
  public static final int NEW = 50;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int MOD = 36;
  public static final int NEQ = 39;
  public static final int BREAK = 29;
  public static final int IDENT = 17;
  public static final int VOID = 16;
  public static final int EQ = 38;
  public static final int SWITCH = 25;
  public static final int LOE = 43;
  public static final int COLON = 26;
  public static final int LBRACE = 3;
  public static final int ELSE = 22;
  public static final int ENUM = 44;
  public static final int READ = 13;
  public static final int WHILE = 24;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 46;
  public static final int PROG = 2;
  public static final int LBOX = 10;
  public static final int QUESTION = 37;
  public static final int BOOL_CONST = 18;
  public static final int GR = 40;
  public static final int PRINT = 12;
  public static final int DO = 23;
  public static final int NUMBER_CONST = 20;
}

