
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  /* key words */
  public static final int PROG = 2;
  public static final int BREAK = 3;
  public static final int CLASS = 4;
  public static final int ENUM = 5;
  public static final int ELSE = 6;
  public static final int CONST = 7;
  public static final int IF = 8;
  public static final int DO = 9;
  public static final int WHILE = 10;
  public static final int NEW = 11;
  public static final int PRINT = 12;
  public static final int READ = 13;
  public static final int RETURN = 14;
  public static final int VOID = 15;
  public static final int CONTINUE = 16;
  
  /* operators */
  public static final int PLUS = 17;
  public static final int PLUSPLUS = 18;
  public static final int MINUS = 19;
  public static final int MINUSMINUS = 20;
  public static final int MUL = 21;
  public static final int DIV = 22;
  public static final int MOD = 23;
  public static final int EQ = 24;
  public static final int NEQ = 25;
  public static final int GR = 26;
  public static final int GRE = 27;
  public static final int LO = 28;
  public static final int LOE = 29;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int EQUAL = 32;
  public static final int SEMI = 33;
  public static final int FULL = 34;
  public static final int COMMA = 35;
  public static final int LBRACE = 36;
  public static final int RBRACE = 37;
  public static final int LPAREN = 38;
  public static final int RPAREN = 39;
  public static final int LBOX = 40;
  public static final int RBOX = 41;
  public static final int QUESTION = 42;
  public static final int COLON = 43;
  
  /*tokens*/
  public static final int NUMBER_CONST = 44;
  public static final int IDENT = 45;
  public static final int BOOL_CONST = 46;
  public static final int CHAR_CONST = 47;
  
  /*C deo*/
  public static final int SWITCH = 48;
  public static final int EXTENDS = 49;
  public static final int CASE = 50;
  
}

